### ISSUE TITLE
2.x: Device becomes out of space after 3 updates

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#125] opened 2016-11-14 15:55 UTC
Device type: TS4900
resinOS version: Resin OS 2.0.0-beta.2
supevisor: 2.7.1

**error in dashboard**
After third update we got 

>failed: Error applying device configuration: Error: update "deviceConfig" set "targetValues" = '{"RESIN_SUPERVISOR_DELTA":"1"}' - SQLITE_FULL: database or disk is full

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_t1z)

**Comment by agherzan** [comment] 2016-11-14 16:02
@shaunmulligan we need a testing image with which we can reproduce the problem.

**Comment by shaunmulligan** [comment] 2016-12-19 14:52
@agherzan we now have their dockerfile (attached in front thread), so we need to assign someone to investigate.

**Comment by agherzan** [comment] 2016-12-20 13:24
Yes @shaunmulligan . @josephroberts is working on this.

**Comment by agherzan** [comment] 2017-02-09 11:15
@josephroberts what happened to this bug?

**Comment by josephroberts** [comment] 2017-02-09 13:13
@agherzan I spent a long time trying to repro and was never able to. There are some notes in the front thread.

**Comment by shaunmulligan** [comment] 2017-02-20 13:56
I believe this most likely has been resolved by new changes in the supervisor 3.x version as new fixes for deltas on AUFS were added.

**Comment by agherzan** [comment] 2017-03-01 02:50
I will close this as @josephroberts was not able to reproduce.

**Closed by agherzan** 2017-03-01 02:50 UTC
Labels: board/ts4900, prio/fastlane, type/bug
