### ISSUE TITLE
SOCKS proxy test

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#369] opened 2017-08-02 12:23 UTC
# Description 
This tests internet connectivity when using a SOCKS proxy.

# Steps to reproduce issue 
# 1 - Execute on the target device:

`# mkdir -p /mnt/boot/system-proxy/`

On the target device (ssh into the hostOS) create this file and replace the <SERVER IP> with the one of the host which will have the proxy server:

` # cat <<'EOF'>> /mnt/boot/system-proxy/redsocks.conf `
` base {`
`   log_debug = off;`
`   log_info = on;`
`   log = stderr;`
`   daemon = off;`
`   redirector = iptables;`
` }`

` redsocks {`
`   type = socks5;`
`   ip = <SERVER IP>;`
`   port = 8123;`
`   local_ip = 127.0.0.1;`
`   local_port = 12345;`
` }`
` EOF`

`# reboot`

# 2 - On a server host machine (your development machine for example) located in the same network, install the ssh server package and start the ssh server daemon.

Then, on the server(your development machine for example), start a ssh tunnel (SOCKS proxy):
`$ timeout -sINT 40s ssh -D 0.0.0.0:8123 -C -N <USER>@localhost`

# 3 - Clean-up.

Execute on the target device (on the hostOS):

`# rm -rf /mnt/boot/system-proxy && reboot`

# Expected result 
1 - The device should reboot and remain offline in the dashboard.

2 - The device should appear as online in the dashboard in the next 40 seconds and then go offline.

3 - The device should reboot and then appear online in the dashboard once booted up.

# Actual result 
Device comes online even when the proxy server is not turned on, but strange behaviour, some parts work, some parts don't. Can connect over VPN, but e.g. LED blink does not work and nor there are any application logs (but there are some supervisor logs...). Reboot works, howerver.

# Other information 
- Reported by: Gergely Imreh 

- Test configuration: RaspberryPi 1 

- Test case number: TC25 

- Test run: [https://resinio.testlodge.com/projects/16238/runs/276578?tab=2&run_section_id=349929&executed_case_id=12173952#executed_case_12173952](https://resinio.testlodge.com/projects/16238/runs/276578?tab=2&run_section_id=349929&executed_case_id=12173952#executed_case_12173952)

**Comment by imrehg** [comment] 2017-08-02 12:24
Duplicate of #368 (failed both on Pi Zero and Pi1), submitted it twice by accident.

**Closed by imrehg** 2017-08-02 12:24 UTC
