### ISSUE TITLE
Jenkins builds fail randomly to pull supervisor image

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#279] opened 2017-04-19 22:17 UTC
Log

```
open /var/lib/docker/tmp/GetImageBlob084191237: no such file or directory
open /var/lib/docker/tmp/GetImageBlob084191237: no such file or directory
ERROR: resin-supervisor-disk: No local supervisor images found.
ERROR: 
ERROR: Task 237 (/yocto/resin-board/build/../layers/meta-resin/meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb, do_package_write_rpm) failed with exit code '1'
ERROR: resin-supervisor-disk: No local supervisor images found.
ERROR: 
ERROR: Task 232 (/yocto/resin-board/build/../layers/meta-resin/meta-resin-common/recipes-containers/docker-disk/docker-resin-supervisor-disk.bb, do_package_qa) failed with exit code '1'
``

Failed log: https://jenkins.dev.resin.io/job/yocto-odroid-ux3/1875/console

**Comment by willnewton** [comment] 2017-04-27 10:00
I believe this issue is caused by a cleanup cron job on the build slaves deleting volumes too aggressively. There's a PR for a probable fix here: https://github.com/resin-io/resin-containers/pull/154

**Comment by willnewton** [comment] 2017-05-02 13:44
This change has now been merged, so hopefully this is fixed.
https://github.com/resin-io/resin-containers/pull/157

**Closed by willnewton** 2017-05-02 13:44 UTC
