### ISSUE TITLE
Add wifi support on RPI Zero Wifi

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#220] opened 2017-03-02 01:10 UTC
Connected to https://github.com/resin-os/resin-os-device-support/issues/4

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_19r9)

**Comment by agherzan** [comment] 2017-03-14 21:06
Reopening this as it seems that it was not fixed only by having the firmware available. It needs dtb too.

**Comment by pimterry** [comment] 2017-03-16 12:34
Relates to https://github.com/resin-os/resinos/issues/231

**Comment by telphan** [comment] 2017-03-30 09:52
Realtes to #245

**Comment by telphan** [comment] 2017-03-30 10:57
Relates to raspberrypi/firmware#785

**Comment by lfarkas** [comment] 2017-04-05 12:55
does the latest resin image ie: 2.0.0+rev2-4.1.1-42b3340f8c2c contain support for pi zero w? since i'm just try it and doesn't seems so.

**Comment by agherzan** [comment] 2017-04-05 12:58
No @lfarkas . This issue will be updated when that happens.

**Comment by muchanem** [comment] 2017-04-13 00:44
Will this be fixed by v2.0.0+rev3?

**Closed** 2017-04-25 13:03 UTC

**Comment by RyanBalfanz** [comment] 2017-05-12 03:16
Any updates on this? I'm still not able to use a Pi Zero W with Resin.

**Comment by telphan** [comment] 2017-05-12 06:50
@RyanBalfanz we are in the process of releasing. The new 2.0.3 will include Pi Zero W. The update should hit the Pi family later today.

**Comment by RyanBalfanz** [comment] 2017-05-12 22:52
@telphan That's great news! Thanks for the update!

**Comment by telphan** [comment] 2017-05-15 15:18
@RyanBalfanz Just want to let you know that we have release on Friday as scheduled. Enjoy the new Pi Zero W support.

**Comment by RyanBalfanz** [comment] 2017-05-15 19:53
@telphan Confirmed! I tested the latest release this past weekend on a Zero W using WiFi and it worked perfectly. Thanks for the update!

**Comment by hellais** [comment] 2017-09-28 23:51
Which dev image can be downloaded that will support Pi Zero W?

**Comment by agherzan** [comment] 2017-10-30 12:50
@hellais Sorry for the late answer. I confirm that is indeed the correct image.
