### ISSUE TITLE
Request for the download files to be named differently

### ISSUE THREAD

**Issue by lurch** [resin-os/resinos#12] opened 2016-10-12 10:01 UTC
I'm not sure if this is the right repo for this issue, let me know if you'd like me to submit it elsewhere instead...

Currently, every single file on https://resinos.io/#downloads is named `resin-dev.zip`, just located in a different subdirectory on the https://files.resin.io/ server. This means that if you want to download resinOS for multiple device types, you end up with files named like `resin-dev.zip`, `resin-dev (1).zip`, `resin-dev (2).zip` etc. in your Downloads folder, and you have to manually rename them (if you can even remember which is which!)

It would be _much_ more convenient if the files were instead named uniquely, to avoid this problem - perhaps something like `resin-dev_raspberry-pi_2.0.0-beta.1.zip`.
(I guess this could be done with some symlinks on the webserver, if you don't want to change your 'build system'?)

And on a small side-note, it seems strange that the RPi1 image is https://files.resin.io/images/raspberry-pi/2.0.0-beta.1/resin-dev.zip , the RPi2 image is https://files.resin.io/images/raspberry-pi2/2.0.0-beta.1/resin-dev.zip and the RPi3 image is https://files.resin.io/images/raspberrypi3/2.0.0-beta.1/resin-dev.zip . For consistency with the other two, shouldn't that last URL be using `raspberry-pi3` rather than `raspberrypi3`?

**Comment by shaunmulligan** [comment] 2016-10-12 10:51
@lurch this is as good a place as any to submit it. In general this repo will be the central point to raise issues on any resinOS issues. 

I'm sure we can sort something out with the URLs, and I would personally love it because I share your pain on the issue. @petrosagg is there a way we can easily have the device name and version number in the download name?

With regards to the inconsistency, its unfortunately a legacy issue from changing naming schemes in resin.io, but we are working to make all the naming consistent across board types.

**Comment by lurch** [comment] 2016-10-12 10:54
> With regards to the inconsistency, its unfortunately a legacy issue from changing naming schemes in resin.io, but we are working to make all the naming consistent across board types.

That could possibly also be 'externally fixed' (while still being inconsistent internally) with a symlink? (unless of course the inconsistency goes much deeper than just the filename)

**Comment by lurch** [comment] 2016-10-12 10:59
> @lurch this is as good a place as any to submit it. In general this repo will be the central point to raise issues on any resinOS issues.

Then perhaps https://resinos.io/docs/contrib/#testing-and-bug-reports should link to this repo, rather than https://github.com/resin-os/meta-resin/issues ?

**Comment by lurch** [comment] 2016-10-14 08:25
...and having just seen #22 it occurs to me that the filenames should probably include 'resinos' rather than just 'resin'. Which would make my earlier example `resinos-dev_raspberry-pi_2.0.0-beta.1.zip`

**Comment by alexandrosm** [comment] 2016-10-14 14:33
this seems intuitively correct. The only thing I would alter is to remove
the dot between "beta" and "1", but that's just aesthetics.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by willnewton** [comment] 2017-04-18 09:59
Closing as duplicate of #161

**Closed by willnewton** 2017-04-18 09:59 UTC
