### ISSUE TITLE
Support channels 12 & 13 for WiFi on Pi Zero W

### ISSUE THREAD

**Issue by Jbithell** [resin-os/resinos#309] opened 2017-05-16 16:58 UTC
**Raspberry Pi Zero W not supporting WiFi Channels 12 & 13**

Steps to reproduce

1. Flashed image to sd card (`resin-[PROJECT NAME]-2.0.3+rev1-4.2.2-8e116ee80767.img`) using Etcher 
2. Setup pi in location known to be within WiFi range
3. 4 flash pattern on Pi status light (`*_*_*_*____*_*_*_*____`)
5. Changed wifi router channel from `Auto` (was then 12) to `11` _(TP Link Archer C20i)_
6. Hard reboot Pi
7. Connects to resin dashboard and works
8. Changed wifi router channel to `13`
9. _Some delay_
10. 4 flash sequence (`*_*_*_*____*_*_*_*____`)
11. Hard reboot pi
12. 4 flash sequence (`*_*_*_*____*_*_*_*____`)

It's a brand new Pi Zero W `v1.1` and I'm planning to deploy to a location where I won't be able to change the WiFi channel and I'd rather not risk it being changed automatically due to network traffic, and therefore the Pi will loose connection to Resin.io

This was a [known issue](https://github.com/raspberrypi/linux/issues/1355) in Raspberry Pi 4.1.20 firmware

**Comment by Jbithell** [comment] 2017-05-16 17:19
Re-tested on fresh image with `-dev` but issue persistent

**Comment by agherzan** [comment] 2017-05-17 11:03
This is actually an interesting problem. It seems like at boot the `Regulatory domain` country is set to `unset`. Which doesn't allow channels 11 and 12 on 2.4Ghz.

```
root@bb21c96:~# iwlist channel 
wlan0     11 channels in total; available frequencies :
          Channel 01 : 2.412 GHz
          Channel 02 : 2.417 GHz
          Channel 03 : 2.422 GHz
          Channel 04 : 2.427 GHz
          Channel 05 : 2.432 GHz
          Channel 06 : 2.437 GHz
          Channel 07 : 2.442 GHz
          Channel 08 : 2.447 GHz
          Channel 09 : 2.452 GHz
          Channel 10 : 2.457 GHz
          Channel 11 : 2.462 GHz
```

As soon as the device connects to the network the country gets updated and channels 12/13 unlocked:
```
root@bb21c96:~# iwlist channel 
wlan0     13 channels in total; available frequencies :
          Channel 01 : 2.412 GHz
          Channel 02 : 2.417 GHz
          Channel 03 : 2.422 GHz
          Channel 04 : 2.427 GHz
          Channel 05 : 2.432 GHz
          Channel 06 : 2.437 GHz
          Channel 07 : 2.442 GHz
          Channel 08 : 2.447 GHz
          Channel 09 : 2.452 GHz
          Channel 10 : 2.457 GHz
          Channel 11 : 2.462 GHz
          Channel 12 : 2.467 GHz
          Channel 13 : 2.472 GHz
```

**Comment by agherzan** [comment] 2017-05-17 14:53
So the problem goes like this. cfg80211 sets the regulatory domain as world. https://github.com/raspberrypi/linux/blob/204050d0eafb565b68abf512710036c10ef1bd23/net/wireless/reg.c#L261 . Generally this is fine because wpa should update the country based on configuration. The problem is that we use the dbus interface of wpa because nm triggers it when needed. So even if you set a default value for `country` in wpa_supplicant.conf it won't work. wpa_supplicant will only update when it actually connects. There are two ways of fixing this as far as I can tell:
1. run a script/service which uses iw based on an entry in config.json - similar to what @michal-mazurek proposed
2. set an additional default country for cfg80211 (world will always be used anyway) - `options cfg80211 ieee80211_regdom=XX` in `/etc/modprobe.d/cfg80211.conf` based on an entry in config.json

In either case we need to allow people to set this from the UI - otherwise we are in a chicken and the egg issue.

If we go to the iw option, the tool is on arm 144K. 
If we go for driver configuration we need to make sure it is configured early enough for the driver to pick it up.

**Comment by Jbithell** [comment] 2017-05-20 13:55
I'm planning to deploy the Pi Zero W to a client site the week after next - any thoughts on how long these fixes normally take? I'd imagine if it involved changing Resin UI it would take a while?

**Comment by michal-mazurek** [comment] 2017-05-24 09:32
We're working on a solution, but we can't commit to a particular date for now.

**Comment by agherzan** [comment] 2017-06-05 14:32
Fix was merged and released in 2.0.5. As soon as raspberrypi images will include meta-resin 2.0.5 (which should happen soon), you will be able to configure the regulatory country by setting the correct entry in config.json.

**Closed by agherzan** 2017-06-05 14:32 UTC

**Comment by Jbithell** [comment] 2017-06-05 16:59
That's great @agherzan thanks for all you and your teams help on this - what is the name of the setting that needs to be set?

**Comment by agherzan** [comment] 2017-06-05 17:31
`country`. @shaunmulligan shall we document this?

**Comment by shaunmulligan** [comment] 2017-06-05 17:45
Yup @agherzan , I think @zwalchuk had already ticketed it up to be documented.

**Comment by agherzan** [comment] 2017-06-06 11:22
@zwalchuk please add a reference to this issue too. Thank you.

**Comment by hedss** [comment] 2017-06-09 14:25
@Jbithell Hi there. This has now been released to production and is present in resinOS versions 2.0.5 onwards.

**Comment by Jbithell** [comment] 2017-06-09 20:40
Thanks @hedss - I'll just wait on https://github.com/resin-io/docs/issues/523 to learn more - thanks to everyone on the thread for all their hard work!
