### ISSUE TITLE
Raspberry Pi Zero W not working.

### ISSUE THREAD

**Issue by muchanem** [resin-os/resinos#269] opened 2017-04-13 00:22 UTC
The pi will start up and show the ResinOS logo and everything and with then will stop running with these two messages last:

- ipv6 addrconf(netdev_up): docker0: link is not ready
- aufus au_opts_verify:1597:docker[748]: dirperm1 breaks the protection by the permission bits on the lower branch

I think this is the root of the problem. I am running ResinOS 2.0.0+rev2. Using wifi to connect to the internet.

**Comment by agherzan** [comment] 2017-04-13 00:36
Hi @muchanem . We are aware of the issue with Pi0 WiFi and currently we don't support this board. We are though actively working in getting this supported soon. I will close this issue though as a duplicate of https://github.com/resin-os/resinos/issues/220 .

**Closed** 2017-04-13 00:36 UTC
