### ISSUE TITLE
built-in BLE on rpi 3 

### ISSUE THREAD

**Issue by hobochild** [resin-os/resinos#199] opened 2017-02-09 12:52 UTC
version: 2.0.0-beta.1
Has anyone tested built-in wifi on rpi3 with resinos? 

@cskiraly has reported https://github.com/Agile-IoT/agile-resin/issues/9 that it is not working. 

> The linked resinOS image is not handling the RPi3 BLE adapter. hciconfig shows nothing. Otherwise, with an external dongle, bluetooth works fine.

I'll try test later today when I have a device on hand. Unless @agherzan @floion are already aware potential problems?

**Comment by agherzan** [comment] 2017-02-15 22:20
I know @josephroberts did some work on this.

**Comment by josephroberts** [comment] 2017-02-16 07:55
@craig-mulligan @agherzan [this](https://github.com/resin-io-projects/rpi3-bluetooth) works fine on managed resinOS 2.0 and I expect it would be the same on managed.

**Comment by craig-mulligan** [comment] 2017-02-16 12:57
Ah yes, I remember it needed a patch. Thanks @josephroberts

**Comment by cskiraly** [comment] 2017-02-17 09:22
In other words, the magic command is `/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -`
Thanks!

I think this should be part of the base image.

**Comment by cskiraly** [comment] 2017-03-09 09:38
@agherzan was this already included in https://github.com/resin-os/resin-raspberrypi ?

**Comment by agherzan** [comment] 2017-03-14 21:01
I'm not sure what's the problem. Can someone clarify what's the problem and/or what's expected?

**Comment by craig-mulligan** [comment] 2017-04-05 09:22
@agherzan the problem is anytime you want to use the built-in ble on rpi3 you have to run `/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -a` sometimes a couple times before it works. 

I think @josephroberts is suggesting we put that command in our base images and @cskiraly is suggesting adding it to the host?

**Comment by agherzan** [comment] 2017-04-05 11:45
The serial device /dev/ttyAMA0 is dependent what what serial is used for bluetooth. It can be either AMA0 or S0 depending on the overlay used.

**Comment by lurch** [comment] 2017-04-05 11:57
I believe in the official Raspbian distro, "some mechanism" (dunno whether this is firmware / kernel / devicetree / udev) is in place that sets up `/dev/serial0` and `/dev/serial1` as 'persistent' serial aliases that dynamically point to either AMA0 or S0 as appropriate, depending on which overlay you're using.
(Can't remember the exact details, as it's not something I've looked at in depth)

**Comment by agherzan** [comment] 2017-04-05 11:58
Sure, we can definitely do that too.

**Comment by mihalski** [comment] 2017-05-22 09:41
I'm currently using hassio which is built on top of resinos and I'm running into a/the bluetooth problem. No hci0 device. I've tried the instructions here but didn't get very far.
```
root@hassio:~# /usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
bcm43xx_init
Flash firmware /lib/firmware/brcm/BCM43430A1.hcd
Set Controller UART speed to 921600 bit/s
Device setup complete
root@hassio:~# hcitool scan
Device is not available: No such device
```
I tried running it again as suggested but then I just got:
```
/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
bcm43xx_init
Failed to write reset command
Can't initialize device: Success
```
I'm hoping to use bluetooth inside the docker container running on this system (if that it as all possible).

Also, not at all clear whether the https://github.com/resin-os/resin-raspberrypi link is relevant to my situation.

Thank you in advance.

Regards,
Michal

**Comment by shaunmulligan** [comment] 2017-05-22 17:47
Hi @mihalski 
How are you running the containers from hassio. I believe in order to use BLE from within a container, you need to make sure the container runs with host networking, or that the bluetooth interface is included in the network namespace of the container. 

On resin.io we currently run the containers with the `--net=host` option, so bluetooth works.

**Comment by mihalski** [comment] 2017-05-22 22:03
Yes they run with --net=host.

The problem is the host doesn't have working bluetooth by default. I found that I could get it working with the following commands:
```
modprobe btusb
/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
hciconfig hci0 up
```
Is there any chance that this could be integrated within resinos for raspberrypi3?

**Comment by cskiraly** [comment] 2017-05-23 07:04
@mihalski I never needed the modprobe. Otherwise I agree, +1 for having this already on in the image!

**Comment by mihalski** [comment] 2017-05-23 07:06
@cskiraly For me the btusb module is not loading automatically. It loads for you or you have a different type of bluetooth? Or a different device?

**Comment by cskiraly** [comment] 2017-05-23 10:36
@mihalski I don't have an SD with resin.os with me, but looking at a device with an other OS, I see hci0 up, and the following modules: bluetooth, bnep, btbcm, hci_uart.
I think you don't need btusb for the integrated BLE on the Raspberry Pi 3.

**Comment by mihalski** [comment] 2017-05-24 07:05
@cskiraly I think you are right. It's just the
```
/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
hciconfig hci0 up
```
that is required.

**Comment by mihalski** [comment] 2017-05-31 10:38
Any word on this? Could it be integrated into the next resinos release?

**Comment by agherzan** [comment] 2017-05-31 11:59
@shaunmulligan @lurch From 2.0.2, raspberrypi images provide device symlinks (https://github.com/resin-os/resin-raspberrypi/blob/master/CHANGELOG.md#v202rev1---2017-04-24) .

**Comment by mihalski** [comment] 2017-05-31 14:27
Does that mean that the above mentioned commands can be performed WITHIN a container to provide bluetooth functionality?

**Comment by agherzan** [comment] 2017-05-31 14:33
@craig-mulligan , this sounds to me like an issue when using bluetooth on resinOS unmanaged. Did you manage to get to any conclusion since you opened this bug?

@mihalski No. That would help if we decide to bring in the hostOS the bluetooth initialisation.

**Comment by andreipopovici** [comment] 2017-06-01 10:04
Just like @mihalski, I'm a hassio user with a similar problem, although slightly different.

I'm disabling BT using an overlay (`pi3-disable-bt`) in config.txt, because I'm using a RaZberry board that needs to access the UART on GPIO pins 14-15. The overlay frees the pins and I can see `/dev/ttyAMA0' on the host (hassio). However, inside the Alpine-based docker container, I see nothing except `/dev/tty`.

What am I missing here? Do I need to mount `/dev/ttyAMA0` when running the container?

**Comment by shaunmulligan** [comment] 2017-06-01 11:49
@andreipopovici yeah, I think you would need to do something like `docker run <imageId> --device /dev/ttyAMA0` assuming you are running unprivileged and that `/dev/ttyAMA0` exists in the hostOS `/dev`

**Comment by andreipopovici** [comment] 2017-06-03 14:50
@shaunmulligan That's what the `hassio` developer (@pvizeli) did in [release 0.35](https://github.com/home-assistant/hassio/commit/df8afb3337d0d8a704e07a1a5d0294f039bd29e8). It allows mounting a device into the `homeassistant` docker image and works great.

**Comment by pvizeli** [comment] 2017-06-07 08:08
We create now a hass.io docker that are able to manage bluetooth from a container to other containers: https://github.com/home-assistant/hassio-addons/tree/master/bluetooth_bcm43xx . I think this topic os now close for hassio users. Thanks for giving support to us.

**Comment by floion** [comment] 2017-06-27 05:10
Hi all, can this be closed now? Is there any further action needed here @pvizeli @andreipopovici @mihalski @cskiraly @craig-mulligan ?

**Comment by cskiraly** [comment] 2017-06-27 08:12
@floion the topic is not hassio specific, therefore no, it is not solved. We know there are workarounds. The question is whether resinOS wants to expose the hci0 directly when it is available on the platform, or prefers to leave this to the user. As an OS user, I would expect hci0 to be exposed directly by the OS.

**Comment by agherzan** [comment] 2017-06-28 13:32
In the past we have't done this because the serial device for Bluetooth could have been configured though a dtb overlay. Now we are using udev aliases which are persistent no matter the actual serial device is the Bluetooth working on (serial0/serial1). I think given this, we can start having this provided by the OS. @shaunmulligan @petrosagg Any comments against this? Otherwise, @cskiraly would you be able to push a PR towards resin-raspberrypi?

**Comment by petrosagg** [comment] 2017-07-02 07:08
@agherzan why doesn't the presence of the DTB automatically trigger loading of the kernel module and enablement of hci0?

**Comment by agherzan** [comment] 2017-07-11 13:25
The hciattach binary attaches a serial device to the Bluez Stack. I don't think you can do that from a dtb automatically.

**Comment by petrosagg** [comment] 2017-07-14 06:06
could we use a udev rule then?

**Comment by lurch** [comment] 2017-07-14 10:40
Presumably such a udev rule would need to query the loaded DTBs, to determine whether either of the UARTs are connected to the Bluetooth module or not?

**Comment by cskiraly** [comment] 2017-10-06 10:49
@shaunmulligan @agherzan  Just adding `/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -` to https://github.com/resin-os/resin-raspberrypi/blob/master/layers/meta-resin-raspberrypi/recipes-support/resin-init/files/resin-init-board works for me. The only thing I miss is a check for the RPi version, since this is only needed on RRi3.  
Is there any reason not to apply this solution?

**Comment by cskiraly** [comment] 2017-10-06 11:30
@shaunmulligan @agherzan  Just adding `/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -` to https://github.com/resin-os/resin-raspberrypi/blob/master/layers/meta-resin-raspberrypi/recipes-support/resin-init/files/resin-init-board works for me. The only thing I miss is a check for the RPi version, since this is only needed on RRi3.  
Is there any reason not to apply this solution?

**Comment by floion** [comment] 2017-10-06 14:43
We will have ble enabled by default for rpi3 in the near future

**Comment by agherzan** [comment] 2017-10-30 12:58
@floion was this change committed?

**Comment by floion** [comment] 2017-10-31 07:50
No. Once this gets fixed this ticket will get updated

**Comment by curcuz** [comment] 2017-12-13 08:51
@floion any update on this?

**Comment by floion** [comment] 2017-12-13 09:00
not yet

**Comment by dfsnow** [comment] 2017-12-27 08:09
I'm having the exact issue as above:

```
/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
bcm43xx_init
Failed to write reset command
Can't initialize device: Success
```

**Comment by floion** [comment] 2017-12-30 20:14
We will have this hopefully fixed in the following week or two

**Comment by floion** [comment] 2018-01-08 10:04
Should be fixed by https://github.com/resin-os/resin-raspberrypi/pull/156

**Comment by LubergAlexander** [comment] 2018-01-08 18:37
@floion is this already available in production? if not - do you know when?

**Comment by floion** [comment] 2018-01-09 03:33
Not yet deployed to production. A conservative estimate would be sometimes next week

**Comment by shaunmulligan** [comment] 2018-02-27 12:00
@floion this has now been deployed in resinOS 2.9.3 on the rpi3 correct?

**Comment by floion** [comment] 2018-02-27 14:17
Yes @shaunmulligan

**Closed by floion** 2018-02-27 14:17 UTC
