### ISSUE TITLE
Creating a file and rebooting doesn't flash the fs buffers

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#146] opened 2016-12-12 10:13 UTC

**Comment by floion** [comment] 2016-12-12 10:26
This is observed when using the webterminal on a rpi3.
User uses nano on the webterminal, creates a text file and writes some small amount o data in it (10-15 lines), saves the file and then issues a "reboot" command from the same webterminal. Upon reboot and the restart of the application, user notices the file is not there anymore.
If the "reboot" command is after a "sync" command or the reboot command is issued after 1 minute, then the buffers seem to be flushed to disks as expected.
This should be tried to be replicated on the host OS level, on the resin-data partition using the same same procedure.

**Comment by michal-mazurek** [comment] 2016-12-13 11:34
I cannot recreate this on 2.0.0-beta.7. This happens only when I unplug the device, which is actually a feature (async option). What version was this observed on?

**Comment by agherzan** [comment] 2016-12-13 15:57
@michal-mazurek can you try to reproduce on 1.X. I'm pretty sure @floion reproduced it on the 1.X line.

**Comment by michal-mazurek** [comment] 2016-12-14 07:49
I tried 2.0.0-beta.7, 1.24 and 1.22.1 and couldn't reproduce this behaviour, I tried ~ and /data. What is the partition and the OS version that is used?

**Comment by floion** [comment] 2016-12-14 15:23
It should be on a 1.X image, rpi3 @michal-mazurek

**Comment by floion** [comment] 2016-12-20 04:32
So this is a Resin OS 1.21.0, with supervisor 2.8.2
The "reboot" command issued in the webterminal also makes the board reboot, which should not happen. This is an additional issue to that described in the beginning of this issue

**Comment by floion** [comment] 2016-12-20 05:47
In host OS version 1.21 the watchdog is kicking in when reboot is issues from the webterminal, making the board reboot soon after and thus not making the changes persistent.
This is fixed in the latest 1.24 release which is available, so closing this issue now

**Closed by floion** 2016-12-20 05:47 UTC

**Comment by agherzan** [comment] 2016-12-20 13:16
Thanks @floion for validation.
